MVC/Controllers/EnviosController.cs
using Compartido.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using MVC.Models;
using LogicaNegocio.EntidadesNegocio;
using LogicaAccesoDatos.Repositorios;
using LogicaAplicacion.Interfaces.UsuarioInterfaces;
using LogicaNegocio.ExcepcionesEntidades;
using System.Security.Claims;
using LogicaAplicacion.Interfaces.AgenciaInterfaces;
using Microsoft.AspNetCore.Mvc.Rendering;
using LogicaAplicacion.AplicacionCasosUso.UsuarioCU;
using LogicaAplicacion.Interfaces.EnvioInterfaces;
using LogicaAplicacion.AplicacionCasosUso.EnvioCU;

namespace MVC.Controllers
{
    public class EnviosController : Controller
    {
        private IGetAllComunes _getAllComunes;
        private IGetAllUrgentes _getAllUrgentes;
        private ICrearUrgente _crearUrgente;
        private ICrearComun _crearComun;
        private IGetUrgenteById _getUrgenteById;
        private IGetComunById _getComunById;
        private IUpdateEnvio _updateEnvio;
        private IGetUserById _getUserById;
        private IGetAgencias _getAgencias;
        private IGetClientes _getClientes;
        private IGetAgenciaById _getAgenciaById;
        private IDeleteUrgente _deleteUrgente;
        private IDeleteComun _deleteComun;
        private IExisteNumTracking _existeNumTracking;

        public EnviosController(IGetAllComunes getAllComunes, IGetAllUrgentes getAllUrgentes,
            ICrearUrgente crearUrgente, ICrearComun crearComun,
            IGetUserById getUserById, IGetAgencias getAgencias, IGetClientes getClientes, IGetAgenciaById getAgenciaById,
            IGetUrgenteById getUrgenteById, IUpdateEnvio updateEnvio, IGetComunById getComunById, IDeleteUrgente deleteUrgente,
            IDeleteComun deleteComun, IExisteNumTracking existeNumTracking)
        {
            _getAllComunes = getAllComunes;
            _getAllUrgentes = getAllUrgentes;
            _crearUrgente = crearUrgente;
            _crearComun = crearComun;
            _getAgenciaById = getAgenciaById;
            _getComunById = getComunById;
            _getUrgenteById = getUrgenteById;
            _updateEnvio = updateEnvio;
            _getUserById = getUserById;
            _getAgencias = getAgencias;
            _getClientes = getClientes;
            _deleteUrgente = deleteUrgente;
            _deleteComun = deleteComun;
            _existeNumTracking = existeNumTracking;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("IdLogueado") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            IEnumerable<ComunDTO> comunesDTO = _getAllComunes.Execute();
            IEnumerable<UrgenteDTO> urgentesDTO = _getAllUrgentes.Execute();
            ViewModelEnviosIndex envios = new ViewModelEnviosIndex(urgentesDTO, comunesDTO);
            return View(envios);
        }

        [HttpGet]
        public IActionResult CreateUrgente()
        {
            if (HttpContext.Session.GetInt32("IdLogueado") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            // Traer a los clientes para select de email
            IEnumerable<UsuarioDTO> clientesDTO = _getClientes.Execute();
            var clientesSelect = clientesDTO.Select(c => new SelectListItem
            {
                Text = c.Email,
                Value = c.Id.ToString()
            }).ToList();

            //Armar viewmodel
            var vm = new ViewModelEnvioUrgente
            {
                urgenteDTO = new UrgenteDTO(),
                Clientes = clientesSelect
            };
            return View(vm);
        }
        [HttpPost]
        public IActionResult CreateUrgente(ViewModelEnvioUrgente vm)
        {
            try
            {
                UrgenteDTO urgenteDTO = vm.urgenteDTO;

                // Buscar el empleado que dio de alta el envio, es decir el que esta logueado
                int empleadoId = (int)HttpContext.Session.GetInt32("IdLogueado");
                UsuarioDTO empleadoDTO = _getUserById.Execute(empleadoId);

                // Buscar cliente por id
                int clienteId = urgenteDTO.ClienteId;
                UsuarioDTO clienteDTO = _getUserById.Execute(clienteId);

                // Asignar propiedades
                urgenteDTO.ClienteId = clienteDTO.Id;
                urgenteDTO.EmpleadoId = empleadoDTO.Id;
                urgenteDTO.Estado = "EN_PROCESO";
                //Asignar numero de tracking unico
                string numTracking;
                do
                {
                    Random random = new Random();
                    numTracking = Math.Round(random.NextDouble() * 900 + 100, 0).ToString();
                } while (_existeNumTracking.Execute(numTracking));
                urgenteDTO.NumTracking = numTracking;


                // Crear el envio
                _crearUrgente.Execute(urgenteDTO);

                //Rederigir al index
                return RedirectToAction("Index");
            }
            catch(EnvioException ex) 
            {
                //Mensaje con el error
                ViewBag.Message = ex.Message;

                // Volver a cargar el vm por si hay error al enviar formulario
                vm.Clientes = _getClientes.Execute().Select(c => new SelectListItem
                {
                    Text = c.Email,
                    Value = c.Id.ToString()
                }).ToList();

                return View(vm);
            }
        }

        [HttpGet]
        public IActionResult CreateComun()
        {
            if (HttpContext.Session.GetInt32("IdLogueado") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            //Traer agencias para select
            IEnumerable<AgenciaDTO> agenciasDTOs = _getAgencias.Execute();

            var agenciasSelect = agenciasDTOs.Select(a => new SelectListItem
            {
                Text = a.Nombre,       
                Value = a.Id.ToString() 
            }).ToList();

            // Traer a los clientes para select de email
            IEnumerable<UsuarioDTO> clientesDTO = _getClientes.Execute();
            var clientesSelect = clientesDTO.Select(c => new SelectListItem
            {
                Text = c.Email,
                Value = c.Id.ToString()
            }).ToList();

            //Armar viewmodel
            var vm = new ViewModelEnvioComun
            {
                comunDTO = new ComunDTO(),
                Agencias = agenciasSelect,
                Clientes = clientesSelect
            };

            return View(vm);
        }
        [HttpPost]
        public IActionResult CreateComun(ViewModelEnvioComun vm)
        {
            try
            {
                ComunDTO comunDTO = vm.comunDTO;

                // Buscar el empleado que dio de alta el envio, es decir el que esta logueado
                int empleadoId = (int)HttpContext.Session.GetInt32("IdLogueado");
                UsuarioDTO empleadoDTO = _getUserById.Execute(empleadoId);

                // Buscar cliente por id
                int clienteId = comunDTO.ClienteId;
                UsuarioDTO clienteDTO = _getUserById.Execute(clienteId);

                // Buscar agencia por id
                int agenciaId = comunDTO.AgenciaId;
                AgenciaDTO agenciaDTO = _getAgenciaById.Execute(agenciaId);

                // Asignar propiedades
                comunDTO.ClienteId = clienteDTO.Id;
                comunDTO.EmpleadoId = empleadoDTO.Id;
                comunDTO.AgenciaId = agenciaDTO.Id;
                comunDTO.Estado = "EN_PROCESO";
                //Asignar numero de tracking unico
                string numTracking;
                do
                {
                    Random random = new Random();
                    numTracking = Math.Round(random.NextDouble() * 900 + 100, 0).ToString();
                } while (_existeNumTracking.Execute(numTracking));
                comunDTO.NumTracking = numTracking;
                
                // Crear el envio
                _crearComun.Execute(comunDTO);

                // Redirigir al index
                return RedirectToAction("Index");
            }
            catch (EnvioException ex)
            {
                //Mensaje con el error
                ViewBag.Message = ex.Message;

                // Volver a cargar la info en caso de error en el envio
                vm.Agencias = _getAgencias.Execute().Select(a => new SelectListItem
                {
                    Text = a.Nombre,
                    Value = a.Id.ToString()
                }).ToList();

                vm.Clientes = _getClientes.Execute().Select(c => new SelectListItem
                {
                    Text = c.Email,
                    Value = c.Id.ToString()
                }).ToList();

                return View(vm);
            }
        }

        [HttpGet]
        public IActionResult EditComun(int id)
        {
            if (HttpContext.Session.GetInt32("IdLogueado") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ComunDTO comunDTO = _getComunById.Execute(id);
            return View(comunDTO);
        }

        [HttpPost]
        public IActionResult EditComun(int id, string comentario)
        {
            try
            {
                //Obtener envio general
                ComunDTO comunDTO = _getComunById.Execute(id);

                //Crear nuevo seguimineto
                Seguimiento nuevoSeguimineto = new Seguimiento
                {
                    Fecha = DateTime.Now,
                    Comentario = comentario,
                    EmpleadoId = comunDTO.EmpleadoId
                };

                //Agregar seguimineto al envio
                comunDTO.Seguimientos.Add(new SeguimientoDTO(nuevoSeguimineto));

                // Actualizar Comun

MVC/Controllers/UsuariosController.cs
using Compartido.DTOs;
using LogicaAplicacion.Interfaces.UsuarioInterfaces;
using LogicaNegocio.EntidadesNegocio;
using LogicaNegocio.ExcepcionesEntidades;
using LogicaNegocio.ValueObject;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class UsuariosController : Controller
    {
        private ICrearUsuario _crearUsuario;
        private IUpdateUsuario _updateUsuario;
        private IDeleteUsuario _deleteUsuario;
        private IGetUserById _userById;
        private IGetUsersByName _usersByName;

        public UsuariosController(ICrearUsuario crearUsuario, 
                                    IGetUserById userById, 
                                    IGetUsersByName usersByName,
                                    IDeleteUsuario deleteUsuario,
                                    IUpdateUsuario updateUsuario)
        {
            _crearUsuario = crearUsuario;
            _userById = userById;
            _usersByName = usersByName;
            _deleteUsuario = deleteUsuario;
            _updateUsuario = updateUsuario;
        }

        public IActionResult Index(string name)
        {
            if(HttpContext.Session.GetInt32("IdLogueado") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            string nombreNoNulo = String.IsNullOrEmpty(name) ? "" : name;
            IEnumerable<UsuarioDTO> usuariosDTO = _usersByName.Execute(nombreNoNulo);
            ViewModelUsuariosIndex viewModel = new ViewModelUsuariosIndex(usuariosDTO);
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (HttpContext.Session.GetInt32("IdLogueado") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Create(UsuarioDTO usuarioDTO)
        {
            try
            {
                _crearUsuario.Execute(usuarioDTO);
                return RedirectToAction(nameof(Index), new {name = ""});
            }
            catch(UsuarioException ex) 
            {
                ViewBag.Message = ex.Message;
                return View();
            }  
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (HttpContext.Session.GetInt32("IdLogueado") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            UsuarioDTO usuarioDTO = _userById.Execute(id);
            return View(usuarioDTO);
        }
        [HttpPost]
        public IActionResult Edit(int id, UsuarioDTO usuarioDTO)
        {
            try
            {
                _updateUsuario.Execute(id, usuarioDTO);
                return RedirectToAction(nameof(Index), new { usuarioDTO });
            }
            catch(UsuarioException ex)
            {
                ViewBag.Message = ex.Message;

                UsuarioDTO mismoUsuarioDTO = _userById.Execute(id);
                return View(mismoUsuarioDTO);
            }
            
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (HttpContext.Session.GetInt32("IdLogueado") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            UsuarioDTO usuarioDTO = _userById.Execute(id);
            return View(usuarioDTO);
        }

        [HttpPost]
        public IActionResult Delete(int id, UsuarioDTO usuarioDTO)
        {
            _deleteUsuario.Execute(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (Context.Session.GetString("RolLogueado") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        }
                        @if(Context.Session.GetString("RolLogueado") == "Administrador" || Context.Session.GetString("RolLogueado") == "Funcionario")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Envios" asp-action="Index">Envios</a>
                            </li>
                            if (Context.Session.GetString("RolLogueado") == "Administrador")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                                </li>
                            }
                            
                        }


                           

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>